### ISSUE TITLE
Could you please set an open source license, if possible. I would like to see the work.

### ISSUE THREAD

**Issue by MahinMuhammad** [OpenClassrooms-Student-Center/7697016-Front-End#1]

**Comment by IndianGhost** [comment]
@MahinMuhammad It's actually an online course about the basics of javascript : https://openclassrooms.com/fr/courses/7697016-creez-des-pages-web-dynamiques-avec-javascript/
You could skip texts and watch videos to have an idea about it (if you're not a french a speaker)

**Comment by MahinMuhammad** [comment]
Thank you very much. This clarifies everything.

**Comment by IndianGhost** [comment]
@MahinMuhammad You're welcome brother
